name: Validate JIRA Issue Key on PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  validate-jira-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR branch name
        run: |
          echo "PR head ref is: ${{ github.head_ref }}"
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Validate JIRA Issue key in branch name
        run: |
          echo "Checking branch: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ [A-Z]{2,}-[0-9]+ ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not contain a valid JIRA issue key (e.g., ABC-123)"
            exit 1
          else
            echo "Valid JIRA issue key found in branch name."
          fi
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
